### ISSUE TITLE
Volume of speaker seems to be different on different systems

### ISSUE THREAD

**Issue by dagwieers** [johnath/beep#1]
Hi,

We'd like to use beep for a small project, but noticed that the speaker volume isn't always as loud as we like to have it. Do you know if it is at all possible to change the volume of the PC speaker, or influence the volume of the sound in any way (eg. increasing the amplitude of the sound) ?

The problem is that in a noisy environment (eg. datacenter) the sound from some systems is barely noticeable.

Thanks in advance.

**Comment by rhonda** [comment]
That highly depends on how your sound system works. These days distributions start to disable the pcspkr kernel module all together and feed the "beeps" through the general audio layer. Depending on which one you use you might be able to control that through alsamixer (which is an ncurses interface to alsa), I would hope pulseaudio and others have similar offerings.

On the other hand, in datacenters and servers therein, one rarely has sound boxes in the machines, so for the "oldstyle" real hardware pc speakers I am not aware of a possibility to regulate the volume. Only option here would be to choose a good manufacturer. I would love to be proven wrong here, though. :)

**Comment by dagwieers** [comment]
Fair enough, we settled for adding visual feedback too ;-)
